apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scylladb:aggregate-to-scyllacluster-member-openshift
  labels:
    rbac.operator.scylladb.com/aggregate-to-scylla-member: "true"
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
