# Version information
scyllaImage:
  tag: 6.1.1
agentImage:
  tag: 3.3.0@sha256:dc2684f51e961d88da5a8eac2d9f165cb7a960cbf91f67f49332e7224317c96b
# Cluster information
developerMode: true
datacenter: us-east-1
racks:
  - name: us-east-1b
    members: 2
    storage:
      capacity: 5Gi
      storageClassName: scylladb-local-xfs
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
