apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scylladb:controller:operator-remote
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.operator.scylladb.com/aggregate-to-scylla-operator-remote: "true"
