apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scylladb:monitoring:grafana
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.operator.scylladb.com/aggregate-to-scylladb-monitoring-grafana: "true"
