[tool.poetry]
name = "scylla-operator-docs"
description = "Scylla Operator Documentation"
version = "0.0.1"
authors = ["ScyllaDB Documentation Contributors"]
package-mode = false

# Pin dependencies to exact versions so CI always produces the same artifacts.
[tool.poetry.dependencies]
python = "^3.10"
pygments = "^2.18.0"
sphinx-scylladb-theme = "^1.8.1"
sphinx-sitemap = "^2.6.0"
sphinx-autobuild = "^2024.4.19"
Sphinx = "^7.3.7"
sphinx-multiversion-scylla = "^0.3.1"
redirects_cli ="^0.1.3"
myst-parser = "^3.0.1"
sphinx-design = "^0.5.0"

[build-system]
requires = ["poetry>=1.8.0"]
build-backend = "poetry.masonry.api"
